<?php

/**
 * Add connection info to this file.
 */

// Allegiance connection information
$alleg_username = 'username';
$alleg_password = 'password';
$alleg_dsn = 'dsn';
$alleg_database = 'database';
$alleg_server = '10.0.0.1';

// Remote database connection info
$webdb_username = 'username';
$webdb_password = 'password';
$webdb_dsn = 'web_dsn';
$webdb_database = 'db';
$webdb_server = 'example.com\db02';
